package es.ramondin.performance.modelOracle.views.common;

import oracle.jbo.Key;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 05 18:16:55 CEST 2014
// ---------------------------------------------------------------------
public interface GraficoVO extends ViewObject {
    String getTipoEjeY();

    String getUnidadesEjeY();

    void setCurrentRowGrafico(Key key);

    Number getMaxDecimales();
}
