package es.ramondin.performance.modelOracle.views.common;

import java.util.ArrayList;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 12 16:14:40 CEST 2014
// ---------------------------------------------------------------------
public interface IshikawaLinVO extends ViewObject {
    Integer getNumCausas();

    ArrayList<Object[]> getCausas();
}
