package es.ramondin.performance.modelOracle.views.common;

import java.util.ArrayList;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 15 12:36:49 CEST 2014
// ---------------------------------------------------------------------
public interface IshikawaVO extends ViewObject {
    ArrayList<Object[]> getEfecto();
}
