package es.ramondin.performance.modelOracle.views.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 30 11:10:32 CEST 2014
// ---------------------------------------------------------------------
public interface PanelVO extends ViewObject {
    Number getNumFilas();

    Number getNumColumnas();
}
