package es.ramondin.performance.modelOracle.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 30 10:48:02 CEST 2014
// ---------------------------------------------------------------------
public interface ParametroVO extends ViewObject {
    String getValor(String param);
}
