package es.ramondin.performance.modelOracle.views.common;

import java.math.BigDecimal;

import java.util.ArrayList;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 24 16:03:28 CEST 2014
// ---------------------------------------------------------------------
public interface PerformanceVO extends ViewObject {

    void setQuerySQL(String querySQL);

    String getQuerySQL();


    void setCamposAnualMensualBD();

    void executeWithParamsEdit(BigDecimal seccion, BigDecimal celula,
                               Integer celulaAgrup, ArrayList celulasExcepcion,
                               Integer anoRuptura, Integer anosHistorico,
                               Integer hastaFecha);
}
