package es.ramondin.performance.modelOracle.views.common;

import oracle.jbo.Key;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 15 15:40:48 CEST 2014
// ---------------------------------------------------------------------
public interface TipoGraficoVO extends ViewObject {
    void setCurrentRowTipoGrafico(Key key);
}
