package es.ramondin.performance.modelOracle.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 13 10:19:39 CEST 2014
// ---------------------------------------------------------------------
public interface TurnoVO extends ViewObject {
    String[] getClavesTurnos();

    Integer[] getIndicesTurnos();
}
