package es.ramondin.performance.modelOracle.views;

import es.ramondin.performance.modelOracle.views.common.IshikawaVO;

import java.util.ArrayList;

import oracle.jbo.RowSetIterator;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 15 12:31:41 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IshikawaVOImpl extends ViewObjectImpl implements IshikawaVO {
    /**
     * This is the default constructor (do not remove).
     */
    public IshikawaVOImpl() {
    }
    
    public ArrayList<Object[]> getEfecto() {
        ArrayList<Object[]> res = null;
        IshikawaVORowImpl rowIshikawa = (IshikawaVORowImpl)this.getCurrentRow();

        if (rowIshikawa != null) {
            res = new ArrayList<Object[]>();
            
            res.add(new Object[] {rowIshikawa.getMishIdTgrEfecto(), rowIshikawa.getMishIdGraEfecto()});
        }

        return res;
    }
}
