package es.ramondin.performance.modelOracle.views;

import es.ramondin.performance.modelOracle.views.common.IshikawaLinVO;

import java.util.ArrayList;

import oracle.jbo.RowSetIterator;
import oracle.jbo.server.ViewObjectImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 12 16:14:30 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IshikawaLinVOImpl extends ViewObjectImpl implements IshikawaLinVO {
    /**
     * This is the default constructor (do not remove).
     */
    public IshikawaLinVOImpl() {
    }

    public Integer getNumCausas() {
        return this.getRowCount();
    }

    public ArrayList<Object[]> getCausas() {
        ArrayList<Object[]> res = null;

        RowSetIterator rsiLineas = this.getRowSetIterator();

        if (rsiLineas.getRowCount() != 0) {
            Object[] resAux;
            IshikawaLinVORowImpl rowIshikawaLin;

            res = new ArrayList<Object[]>();
            
            rsiLineas.reset();

            while (rsiLineas.hasNext()) {
                rowIshikawaLin = (IshikawaLinVORowImpl)rsiLineas.next();
                resAux = new Object[] { rowIshikawaLin.getMishIdTgrCausa(), rowIshikawaLin.getMishIdGraCausa() };

                res.add(resAux);
            }
        }

        return res;
    }
}