package es.ramondin.performance.modelOracle.views;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 30 08:56:58 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PanelLinVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        MpanIdC {
            public Object get(PanelLinVORowImpl obj) {
                return obj.getMpanIdC();
            }

            public void put(PanelLinVORowImpl obj, Object value) {
                obj.setMpanIdC((Number)value);
            }
        }
        ,
        MpanIdL {
            public Object get(PanelLinVORowImpl obj) {
                return obj.getMpanIdL();
            }

            public void put(PanelLinVORowImpl obj, Object value) {
                obj.setMpanIdL((Number)value);
            }
        }
        ,
        MpanIdTipoGra {
            public Object get(PanelLinVORowImpl obj) {
                return obj.getMpanIdTipoGra();
            }

            public void put(PanelLinVORowImpl obj, Object value) {
                obj.setMpanIdTipoGra((String)value);
            }
        }
        ,
        MpanIdGra {
            public Object get(PanelLinVORowImpl obj) {
                return obj.getMpanIdGra();
            }

            public void put(PanelLinVORowImpl obj, Object value) {
                obj.setMpanIdGra((Number)value);
            }
        }
        ,
        MpanPosFila {
            public Object get(PanelLinVORowImpl obj) {
                return obj.getMpanPosFila();
            }

            public void put(PanelLinVORowImpl obj, Object value) {
                obj.setMpanPosFila((Number)value);
            }
        }
        ,
        MpanPosCol {
            public Object get(PanelLinVORowImpl obj) {
                return obj.getMpanPosCol();
            }

            public void put(PanelLinVORowImpl obj, Object value) {
                obj.setMpanPosCol((Number)value);
            }
        }
        ,
        MpanHAlign {
            public Object get(PanelLinVORowImpl obj) {
                return obj.getMpanHAlign();
            }

            public void put(PanelLinVORowImpl obj, Object value) {
                obj.setMpanHAlign((String)value);
            }
        }
        ,
        MpanVAlign {
            public Object get(PanelLinVORowImpl obj) {
                return obj.getMpanVAlign();
            }

            public void put(PanelLinVORowImpl obj, Object value) {
                obj.setMpanVAlign((String)value);
            }
        }
        ,
        MpanColSpan {
            public Object get(PanelLinVORowImpl obj) {
                return obj.getMpanColSpan();
            }

            public void put(PanelLinVORowImpl obj, Object value) {
                obj.setMpanColSpan((Number)value);
            }
        }
        ,
        MpanRowSpan {
            public Object get(PanelLinVORowImpl obj) {
                return obj.getMpanRowSpan();
            }

            public void put(PanelLinVORowImpl obj, Object value) {
                obj.setMpanRowSpan((Number)value);
            }
        }
        ,
        Grafico {
            public Object get(PanelLinVORowImpl obj) {
                return obj.getGrafico();
            }

            public void put(PanelLinVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PanelLinVORowImpl object);

        public abstract void put(PanelLinVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int MPANIDC = AttributesEnum.MpanIdC.index();
    public static final int MPANIDL = AttributesEnum.MpanIdL.index();
    public static final int MPANIDTIPOGRA = AttributesEnum.MpanIdTipoGra.index();
    public static final int MPANIDGRA = AttributesEnum.MpanIdGra.index();
    public static final int MPANPOSFILA = AttributesEnum.MpanPosFila.index();
    public static final int MPANPOSCOL = AttributesEnum.MpanPosCol.index();
    public static final int MPANHALIGN = AttributesEnum.MpanHAlign.index();
    public static final int MPANVALIGN = AttributesEnum.MpanVAlign.index();
    public static final int MPANCOLSPAN = AttributesEnum.MpanColSpan.index();
    public static final int MPANROWSPAN = AttributesEnum.MpanRowSpan.index();
    public static final int GRAFICO = AttributesEnum.Grafico.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PanelLinVORowImpl() {
    }

    /**
     * Gets PanelLinEO entity object.
     * @return the PanelLinEO
     */
    public EntityImpl getPanelLinEO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for MPAN_ID_C using the alias name MpanIdC.
     * @return the MPAN_ID_C
     */
    public Number getMpanIdC() {
        return (Number) getAttributeInternal(MPANIDC);
    }

    /**
     * Sets <code>value</code> as attribute value for MPAN_ID_C using the alias name MpanIdC.
     * @param value value to set the MPAN_ID_C
     */
    public void setMpanIdC(Number value) {
        setAttributeInternal(MPANIDC, value);
    }

    /**
     * Gets the attribute value for MPAN_ID_L using the alias name MpanIdL.
     * @return the MPAN_ID_L
     */
    public Number getMpanIdL() {
        return (Number) getAttributeInternal(MPANIDL);
    }

    /**
     * Sets <code>value</code> as attribute value for MPAN_ID_L using the alias name MpanIdL.
     * @param value value to set the MPAN_ID_L
     */
    public void setMpanIdL(Number value) {
        setAttributeInternal(MPANIDL, value);
    }

    /**
     * Gets the attribute value for MPAN_ID_TIPO_GRA using the alias name MpanIdTipoGra.
     * @return the MPAN_ID_TIPO_GRA
     */
    public String getMpanIdTipoGra() {
        return (String) getAttributeInternal(MPANIDTIPOGRA);
    }

    /**
     * Sets <code>value</code> as attribute value for MPAN_ID_TIPO_GRA using the alias name MpanIdTipoGra.
     * @param value value to set the MPAN_ID_TIPO_GRA
     */
    public void setMpanIdTipoGra(String value) {
        setAttributeInternal(MPANIDTIPOGRA, value);
    }

    /**
     * Gets the attribute value for MPAN_ID_GRA using the alias name MpanIdGra.
     * @return the MPAN_ID_GRA
     */
    public Number getMpanIdGra() {
        return (Number) getAttributeInternal(MPANIDGRA);
    }

    /**
     * Sets <code>value</code> as attribute value for MPAN_ID_GRA using the alias name MpanIdGra.
     * @param value value to set the MPAN_ID_GRA
     */
    public void setMpanIdGra(Number value) {
        setAttributeInternal(MPANIDGRA, value);
    }

    /**
     * Gets the attribute value for MPAN_POS_FILA using the alias name MpanPosFila.
     * @return the MPAN_POS_FILA
     */
    public Number getMpanPosFila() {
        return (Number) getAttributeInternal(MPANPOSFILA);
    }

    /**
     * Sets <code>value</code> as attribute value for MPAN_POS_FILA using the alias name MpanPosFila.
     * @param value value to set the MPAN_POS_FILA
     */
    public void setMpanPosFila(Number value) {
        setAttributeInternal(MPANPOSFILA, value);
    }

    /**
     * Gets the attribute value for MPAN_POS_COL using the alias name MpanPosCol.
     * @return the MPAN_POS_COL
     */
    public Number getMpanPosCol() {
        return (Number) getAttributeInternal(MPANPOSCOL);
    }

    /**
     * Sets <code>value</code> as attribute value for MPAN_POS_COL using the alias name MpanPosCol.
     * @param value value to set the MPAN_POS_COL
     */
    public void setMpanPosCol(Number value) {
        setAttributeInternal(MPANPOSCOL, value);
    }

    /**
     * Gets the attribute value for MPAN_H_ALIGN using the alias name MpanHAlign.
     * @return the MPAN_H_ALIGN
     */
    public String getMpanHAlign() {
        return (String) getAttributeInternal(MPANHALIGN);
    }

    /**
     * Sets <code>value</code> as attribute value for MPAN_H_ALIGN using the alias name MpanHAlign.
     * @param value value to set the MPAN_H_ALIGN
     */
    public void setMpanHAlign(String value) {
        setAttributeInternal(MPANHALIGN, value);
    }

    /**
     * Gets the attribute value for MPAN_V_ALIGN using the alias name MpanVAlign.
     * @return the MPAN_V_ALIGN
     */
    public String getMpanVAlign() {
        return (String) getAttributeInternal(MPANVALIGN);
    }

    /**
     * Sets <code>value</code> as attribute value for MPAN_V_ALIGN using the alias name MpanVAlign.
     * @param value value to set the MPAN_V_ALIGN
     */
    public void setMpanVAlign(String value) {
        setAttributeInternal(MPANVALIGN, value);
    }

    /**
     * Gets the attribute value for MPAN_COL_SPAN using the alias name MpanColSpan.
     * @return the MPAN_COL_SPAN
     */
    public Number getMpanColSpan() {
        return (Number) getAttributeInternal(MPANCOLSPAN);
    }

    /**
     * Sets <code>value</code> as attribute value for MPAN_COL_SPAN using the alias name MpanColSpan.
     * @param value value to set the MPAN_COL_SPAN
     */
    public void setMpanColSpan(Number value) {
        setAttributeInternal(MPANCOLSPAN, value);
    }

    /**
     * Gets the attribute value for MPAN_ROW_SPAN using the alias name MpanRowSpan.
     * @return the MPAN_ROW_SPAN
     */
    public Number getMpanRowSpan() {
        return (Number) getAttributeInternal(MPANROWSPAN);
    }

    /**
     * Sets <code>value</code> as attribute value for MPAN_ROW_SPAN using the alias name MpanRowSpan.
     * @param value value to set the MPAN_ROW_SPAN
     */
    public void setMpanRowSpan(Number value) {
        setAttributeInternal(MPANROWSPAN, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link Grafico.
     */
    public RowIterator getGrafico() {
        return (RowIterator)getAttributeInternal(GRAFICO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
