package es.ramondin.performance.modelOracle.views;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 30 11:04:57 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PanelVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        MpanId {
            public Object get(PanelVORowImpl obj) {
                return obj.getMpanId();
            }

            public void put(PanelVORowImpl obj, Object value) {
                obj.setMpanId((Number)value);
            }
        }
        ,
        MpanDesc {
            public Object get(PanelVORowImpl obj) {
                return obj.getMpanDesc();
            }

            public void put(PanelVORowImpl obj, Object value) {
                obj.setMpanDesc((String)value);
            }
        }
        ,
        MpanNumFilas {
            public Object get(PanelVORowImpl obj) {
                return obj.getMpanNumFilas();
            }

            public void put(PanelVORowImpl obj, Object value) {
                obj.setMpanNumFilas((Number)value);
            }
        }
        ,
        MpanNumCols {
            public Object get(PanelVORowImpl obj) {
                return obj.getMpanNumCols();
            }

            public void put(PanelVORowImpl obj, Object value) {
                obj.setMpanNumCols((Number)value);
            }
        }
        ,
        DescPanelTrans {
            public Object get(PanelVORowImpl obj) {
                return obj.getDescPanelTrans();
            }

            public void put(PanelVORowImpl obj, Object value) {
                obj.setDescPanelTrans((String)value);
            }
        }
        ,
        PanelLin {
            public Object get(PanelVORowImpl obj) {
                return obj.getPanelLin();
            }

            public void put(PanelVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PanelVORowImpl object);

        public abstract void put(PanelVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int MPANID = AttributesEnum.MpanId.index();
    public static final int MPANDESC = AttributesEnum.MpanDesc.index();
    public static final int MPANNUMFILAS = AttributesEnum.MpanNumFilas.index();
    public static final int MPANNUMCOLS = AttributesEnum.MpanNumCols.index();
    public static final int DESCPANELTRANS = AttributesEnum.DescPanelTrans.index();
    public static final int PANELLIN = AttributesEnum.PanelLin.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PanelVORowImpl() {
    }

    /**
     * Gets PanelEO entity object.
     * @return the PanelEO
     */
    public EntityImpl getPanelEO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for MPAN_ID using the alias name MpanId.
     * @return the MPAN_ID
     */
    public Number getMpanId() {
        return (Number) getAttributeInternal(MPANID);
    }

    /**
     * Sets <code>value</code> as attribute value for MPAN_ID using the alias name MpanId.
     * @param value value to set the MPAN_ID
     */
    public void setMpanId(Number value) {
        setAttributeInternal(MPANID, value);
    }

    /**
     * Gets the attribute value for MPAN_DESC using the alias name MpanDesc.
     * @return the MPAN_DESC
     */
    public String getMpanDesc() {
        return (String) getAttributeInternal(MPANDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for MPAN_DESC using the alias name MpanDesc.
     * @param value value to set the MPAN_DESC
     */
    public void setMpanDesc(String value) {
        setAttributeInternal(MPANDESC, value);
    }

    /**
     * Gets the attribute value for MPAN_NUM_FILAS using the alias name MpanNumFilas.
     * @return the MPAN_NUM_FILAS
     */
    public Number getMpanNumFilas() {
        return (Number) getAttributeInternal(MPANNUMFILAS);
    }

    /**
     * Sets <code>value</code> as attribute value for MPAN_NUM_FILAS using the alias name MpanNumFilas.
     * @param value value to set the MPAN_NUM_FILAS
     */
    public void setMpanNumFilas(Number value) {
        setAttributeInternal(MPANNUMFILAS, value);
    }

    /**
     * Gets the attribute value for MPAN_NUM_COLS using the alias name MpanNumCols.
     * @return the MPAN_NUM_COLS
     */
    public Number getMpanNumCols() {
        return (Number) getAttributeInternal(MPANNUMCOLS);
    }

    /**
     * Sets <code>value</code> as attribute value for MPAN_NUM_COLS using the alias name MpanNumCols.
     * @param value value to set the MPAN_NUM_COLS
     */
    public void setMpanNumCols(Number value) {
        setAttributeInternal(MPANNUMCOLS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DescPanelTrans.
     * @return the DescPanelTrans
     */
    public String getDescPanelTrans() {
        return (String) getAttributeInternal(DESCPANELTRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DescPanelTrans.
     * @param value value to set the  DescPanelTrans
     */
    public void setDescPanelTrans(String value) {
        setAttributeInternal(DESCPANELTRANS, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PanelLin.
     */
    public RowIterator getPanelLin() {
        return (RowIterator)getAttributeInternal(PANELLIN);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
