package es.ramondin.performance.modelOracle.views;


import es.ramondin.performance.modelOracle.views.common.PanelLinVO;

import java.util.ArrayList;

import oracle.jbo.RowSetIterator;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 30 08:56:58 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PanelLinVOImpl extends ViewObjectImpl implements PanelLinVO {
    /**
     * This is the default constructor (do not remove).
     */
    public PanelLinVOImpl() {
    }
    
    public Integer getNumLineasPanel() {
        return this.getRowCount();
    }

    public ArrayList<PanelLinVORowImpl> getLineasPanel() {
        ArrayList<PanelLinVORowImpl> res = null;

        RowSetIterator rsiLineas = this.getRowSetIterator();

        if (rsiLineas.getRowCount() != 0) {
            res = new ArrayList<PanelLinVORowImpl>();
            
            PanelLinVORowImpl rowPanelLin = (PanelLinVORowImpl)rsiLineas.first();
            while (rowPanelLin != null) {
                res.add(rowPanelLin);
                rowPanelLin = (PanelLinVORowImpl)rsiLineas.next();
            }
            
            //Restablecemos el iterador
            rsiLineas.reset();
        }

        return res;
    }
}
