package es.ramondin.performance.modelOracle.views;

import es.ramondin.performance.modelOracle.views.common.PanelVO;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 30 11:04:57 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PanelVOImpl extends ViewObjectImpl implements PanelVO {
    /**
     * This is the default constructor (do not remove).
     */
    public PanelVOImpl() {
    }
    
    public Number getNumFilas() {
        return this.getCurrentRow() != null ? ((PanelVORowImpl)this.getCurrentRow()).getMpanNumFilas() : null;
    }
    
    public Number getNumColumnas() {
        return this.getCurrentRow() != null ? ((PanelVORowImpl)this.getCurrentRow()).getMpanNumCols() : null;
    }
}
