package es.ramondin.performance.modelOracle.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 05 16:13:32 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PerformanceVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PerfPeriodo {
            public Object get(PerformanceVORowImpl obj) {
                return obj.getPerfPeriodo();
            }

            public void put(PerformanceVORowImpl obj, Object value) {
                obj.setPerfPeriodo((Number)value);
            }
        }
        ,
        PerfPeriodoEdit {
            public Object get(PerformanceVORowImpl obj) {
                return obj.getPerfPeriodoEdit();
            }

            public void put(PerformanceVORowImpl obj, Object value) {
                obj.setPerfPeriodoEdit((String)value);
            }
        }
        ,
        PerfTipoPeriodo {
            public Object get(PerformanceVORowImpl obj) {
                return obj.getPerfTipoPeriodo();
            }

            public void put(PerformanceVORowImpl obj, Object value) {
                obj.setPerfTipoPeriodo((Number)value);
            }
        }
        ,
        PerfEmpresa {
            public Object get(PerformanceVORowImpl obj) {
                return obj.getPerfEmpresa();
            }

            public void put(PerformanceVORowImpl obj, Object value) {
                obj.setPerfEmpresa((Number)value);
            }
        }
        ,
        PerfSeccion {
            public Object get(PerformanceVORowImpl obj) {
                return obj.getPerfSeccion();
            }

            public void put(PerformanceVORowImpl obj, Object value) {
                obj.setPerfSeccion((Number)value);
            }
        }
        ,
        PerfCelula {
            public Object get(PerformanceVORowImpl obj) {
                return obj.getPerfCelula();
            }

            public void put(PerformanceVORowImpl obj, Object value) {
                obj.setPerfCelula((Number)value);
            }
        }
        ,
        PerfTurno {
            public Object get(PerformanceVORowImpl obj) {
                return obj.getPerfTurno();
            }

            public void put(PerformanceVORowImpl obj, Object value) {
                obj.setPerfTurno((String)value);
            }
        }
        ,
        PerfDatoAnual {
            public Object get(PerformanceVORowImpl obj) {
                return obj.getPerfDatoAnual();
            }

            public void put(PerformanceVORowImpl obj, Object value) {
                obj.setPerfDatoAnual((Number)value);
            }
        }
        ,
        PerfDatoMensual {
            public Object get(PerformanceVORowImpl obj) {
                return obj.getPerfDatoMensual();
            }

            public void put(PerformanceVORowImpl obj, Object value) {
                obj.setPerfDatoMensual((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PerformanceVORowImpl object);

        public abstract void put(PerformanceVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PERFPERIODO = AttributesEnum.PerfPeriodo.index();
    public static final int PERFPERIODOEDIT = AttributesEnum.PerfPeriodoEdit.index();
    public static final int PERFTIPOPERIODO = AttributesEnum.PerfTipoPeriodo.index();
    public static final int PERFEMPRESA = AttributesEnum.PerfEmpresa.index();
    public static final int PERFSECCION = AttributesEnum.PerfSeccion.index();
    public static final int PERFCELULA = AttributesEnum.PerfCelula.index();
    public static final int PERFTURNO = AttributesEnum.PerfTurno.index();
    public static final int PERFDATOANUAL = AttributesEnum.PerfDatoAnual.index();
    public static final int PERFDATOMENSUAL = AttributesEnum.PerfDatoMensual.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PerformanceVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute PerfPeriodo.
     * @return the PerfPeriodo
     */
    public Number getPerfPeriodo() {
        return (Number) getAttributeInternal(PERFPERIODO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PerfPeriodo.
     * @param value value to set the  PerfPeriodo
     */
    public void setPerfPeriodo(Number value) {
        setAttributeInternal(PERFPERIODO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PerfPeriodoEdit.
     * @return the PerfPeriodoEdit
     */
    public String getPerfPeriodoEdit() {
        return (String) getAttributeInternal(PERFPERIODOEDIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PerfPeriodoEdit.
     * @param value value to set the  PerfPeriodoEdit
     */
    public void setPerfPeriodoEdit(String value) {
        setAttributeInternal(PERFPERIODOEDIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PerfTipoPeriodo.
     * @return the PerfTipoPeriodo
     */
    public Number getPerfTipoPeriodo() {
        return (Number) getAttributeInternal(PERFTIPOPERIODO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PerfTipoPeriodo.
     * @param value value to set the  PerfTipoPeriodo
     */
    public void setPerfTipoPeriodo(Number value) {
        setAttributeInternal(PERFTIPOPERIODO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PerfEmpresa.
     * @return the PerfEmpresa
     */
    public Number getPerfEmpresa() {
        return (Number) getAttributeInternal(PERFEMPRESA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PerfEmpresa.
     * @param value value to set the  PerfEmpresa
     */
    public void setPerfEmpresa(Number value) {
        setAttributeInternal(PERFEMPRESA, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PerfSeccion.
     * @return the PerfSeccion
     */
    public Number getPerfSeccion() {
        return (Number) getAttributeInternal(PERFSECCION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PerfSeccion.
     * @param value value to set the  PerfSeccion
     */
    public void setPerfSeccion(Number value) {
        setAttributeInternal(PERFSECCION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PerfCelula.
     * @return the PerfCelula
     */
    public Number getPerfCelula() {
        return (Number) getAttributeInternal(PERFCELULA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PerfCelula.
     * @param value value to set the  PerfCelula
     */
    public void setPerfCelula(Number value) {
        setAttributeInternal(PERFCELULA, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PerfTurno.
     * @return the PerfTurno
     */
    public String getPerfTurno() {
        return (String) getAttributeInternal(PERFTURNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PerfTurno.
     * @param value value to set the  PerfTurno
     */
    public void setPerfTurno(String value) {
        setAttributeInternal(PERFTURNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PerfDatoAnual.
     * @return the PerfDatoAnual
     */
    public Number getPerfDatoAnual() {
        return (Number) getAttributeInternal(PERFDATOANUAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PerfDatoAnual.
     * @param value value to set the  PerfDatoAnual
     */
    public void setPerfDatoAnual(Number value) {
        setAttributeInternal(PERFDATOANUAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PerfDatoMensual.
     * @return the PerfDatoMensual
     */
    public Number getPerfDatoMensual() {
        return (Number) getAttributeInternal(PERFDATOMENSUAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PerfDatoMensual.
     * @param value value to set the  PerfDatoMensual
     */
    public void setPerfDatoMensual(Number value) {
        setAttributeInternal(PERFDATOMENSUAL, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
