package es.ramondin.performance.modelOracle.views;

import es.ramondin.performance.modelOracle.views.common.TipoGraficoVO;

import oracle.jbo.Key;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 15 15:38:07 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TipoGraficoVOImpl extends ViewObjectImpl implements TipoGraficoVO {
    /**
     * This is the default constructor (do not remove).
     */
    public TipoGraficoVOImpl() {
    }
    
    public void setCurrentRowTipoGrafico(Key key) {
        this.setCurrentRow(this.getRow(key));
    }
}
