package es.ramondin.performance.modelOracle.views;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 20 09:33:11 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TipoMarkerVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        TmaTipoMarker {
            public Object get(TipoMarkerVORowImpl obj) {
                return obj.getTmaTipoMarker();
            }

            public void put(TipoMarkerVORowImpl obj, Object value) {
                obj.setTmaTipoMarker((String)value);
            }
        }
        ,
        TmaDescripcion {
            public Object get(TipoMarkerVORowImpl obj) {
                return obj.getTmaDescripcion();
            }

            public void put(TipoMarkerVORowImpl obj, Object value) {
                obj.setTmaDescripcion((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(TipoMarkerVORowImpl object);

        public abstract void put(TipoMarkerVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int TMATIPOMARKER = AttributesEnum.TmaTipoMarker.index();
    public static final int TMADESCRIPCION = AttributesEnum.TmaDescripcion.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TipoMarkerVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute TmaTipoMarker.
     * @return the TmaTipoMarker
     */
    public String getTmaTipoMarker() {
        return (String) getAttributeInternal(TMATIPOMARKER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TmaTipoMarker.
     * @param value value to set the  TmaTipoMarker
     */
    public void setTmaTipoMarker(String value) {
        setAttributeInternal(TMATIPOMARKER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TmaDescripcion.
     * @return the TmaDescripcion
     */
    public String getTmaDescripcion() {
        return (String) getAttributeInternal(TMADESCRIPCION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TmaDescripcion.
     * @param value value to set the  TmaDescripcion
     */
    public void setTmaDescripcion(String value) {
        setAttributeInternal(TMADESCRIPCION, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
