package es.ramondin.performance.modelOracle.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 20 09:33:11 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TipoMarkerVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TipoMarkerVOImpl() {
    }
}
