package es.ramondin.performance.modelOracle.views;

import java.util.Locale;

import oracle.jbo.RowIterator;
import oracle.jbo.common.ResourceBundleDef;
import oracle.jbo.common.StringManager;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 12 09:55:23 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TurnoVORowImpl extends ViewRowImpl {


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PerfTurno,
        TurnoDesc;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PERFTURNO = AttributesEnum.PerfTurno.index();
    public static final int TURNODESC = AttributesEnum.TurnoDesc.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TurnoVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute PerfTurno.
     * @return the PerfTurno
     */
    public String getPerfTurno() {
        return (String) getAttributeInternal(PERFTURNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PerfTurno.
     * @param value value to set the  PerfTurno
     */
    public void setPerfTurno(String value) {
        setAttributeInternal(PERFTURNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TurnoDesc.
     * @return the TurnoDesc
     */
    public String getTurnoDesc() {
        return (String) getAttributeInternal(TURNODESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TurnoDesc.
     * @param value value to set the  TurnoDesc
     */
    public void setTurnoDesc(String value) {
        setAttributeInternal(TURNODESC, value);
    }


    public String getLocalizedValue(String key) {
        ResourceBundleDef resourceDef = this.getResourceBundleDef();
        Locale locale = this.getApplicationModule().getSession().getLocale();

        return StringManager.getLocalizedStringFromResourceDef(resourceDef, key, null, locale, null);
    }
}
