package es.ramondin.performance.modelOracle.views.client;

import es.ramondin.performance.modelOracle.views.common.GraficoVO;

import oracle.jbo.Key;
import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 05 18:16:55 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GraficoVOClient extends ViewUsageImpl implements GraficoVO {
    /**
     * This is the default constructor (do not remove).
     */
    public GraficoVOClient() {
    }


    public String getTipoEjeY() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getTipoEjeY",null,null);
        return (String)_ret;
    }

    public String getUnidadesEjeY() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getUnidadesEjeY",null,null);
        return (String)_ret;
    }

    public void setCurrentRowGrafico(Key key) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"setCurrentRowGrafico",new String [] {"oracle.jbo.Key"},new Object[] {key});
        return;
    }

    public Number getMaxDecimales() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getMaxDecimales",null,null);
        return (Number)_ret;
    }
}
