package es.ramondin.performance.modelOracle.views.client;

import es.ramondin.performance.modelOracle.views.common.IshikawaVO;

import java.util.ArrayList;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 15 12:36:49 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IshikawaVOClient extends ViewUsageImpl implements IshikawaVO {
    /**
     * This is the default constructor (do not remove).
     */
    public IshikawaVOClient() {
    }

    public ArrayList<Object[]> getEfecto() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getEfecto",null,null);
        return (ArrayList<Object[]>)_ret;
    }
}
