package es.ramondin.performance.modelOracle.views.client;

import es.ramondin.performance.modelOracle.views.common.MarkerEspecialVO;

import java.math.BigDecimal;

import java.util.ArrayList;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 19 09:21:49 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MarkerEspecialVOClient extends ViewUsageImpl implements MarkerEspecialVO {
    /**
     * This is the default constructor (do not remove).
     */
    public MarkerEspecialVOClient() {
    }

    public Double[] getValorMarkers() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getValorMarkers",null,null);
        return (Double[])_ret;
    }

    public String[] getTextoMarkers() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getTextoMarkers",null,null);
        return (String[])_ret;
    }


    public void cargaMarkersEsp(BigDecimal seccion, BigDecimal celula, Integer celulaAgrup, ArrayList celulasExcepcion, Integer anoRuptura,
                                Integer anosHistorico, Integer hastaFecha, Boolean desgloseMensual, Boolean mismoPeriodo, Boolean romperPorTurno,
                                String[] turnos) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"cargaMarkersEsp",new String [] {"java.math.BigDecimal","java.math.BigDecimal","java.lang.Integer","java.util.ArrayList","java.lang.Integer","java.lang.Integer","java.lang.Integer","java.lang.Boolean","java.lang.Boolean","java.lang.Boolean","[Ljava.lang.String;"},new Object[] {seccion, celula, celulaAgrup, celulasExcepcion, anoRuptura, anosHistorico, hastaFecha, desgloseMensual, mismoPeriodo, romperPorTurno, turnos});
        return;
    }

    public Double[] getValorMarkersEsp() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getValorMarkersEsp",null,null);
        return (Double[])_ret;
    }

    public String[] getTextoMarkersEsp() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getTextoMarkersEsp",null,null);
        return (String[])_ret;
    }

    public String[] getColorMarkersEspIndependiente() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getColorMarkersEspIndependiente",null,null);
        return (String[])_ret;
    }

    public String[] getColorMarkersEsp() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getColorMarkersEsp",null,null);
        return (String[])_ret;
    }
}
