package es.ramondin.performance.modelOracle.views.client;

import es.ramondin.performance.modelOracle.views.common.MarkerVO;

import java.sql.Date;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 24 16:04:35 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MarkerVOClient extends ViewUsageImpl implements MarkerVO {
    /**
     * This is the default constructor (do not remove).
     */
    public MarkerVOClient() {
    }

    public Double[] getValorMarkers(Number idGrafico, Date desdeFecha) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getValorMarkers",new String [] {"oracle.jbo.domain.Number","java.sql.Date"},new Object[] {idGrafico, desdeFecha});
        return (Double[])_ret;
    }

    public Number getSentidoMejor(Number idGrafico, Date desdeFecha) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getSentidoMejor",new String [] {"oracle.jbo.domain.Number","java.sql.Date"},new Object[] {idGrafico, desdeFecha});
        return (Number)_ret;
    }

    public Double[] getValorMarkers(String idTipoGrafico, Number idGrafico, Date desdeFecha) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getValorMarkers",new String [] {"java.lang.String","oracle.jbo.domain.Number","java.sql.Date"},new Object[] {idTipoGrafico, idGrafico, desdeFecha});
        return (Double[])_ret;
    }

    public Number getSentidoMejor(String idTipoGrafico, Number idGrafico, Date desdeFecha) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getSentidoMejor",new String [] {"java.lang.String","oracle.jbo.domain.Number","java.sql.Date"},new Object[] {idTipoGrafico, idGrafico, desdeFecha});
        return (Number)_ret;
    }

    public Double[] getValorMarkers(Date desdeFecha) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getValorMarkers",new String [] {"java.sql.Date"},new Object[] {desdeFecha});
        return (Double[])_ret;
    }

    public Number getSentidoMejor(Date desdeFecha) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getSentidoMejor",new String [] {"java.sql.Date"},new Object[] {desdeFecha});
        return (Number)_ret;
    }
}
