package es.ramondin.performance.modelOracle.views.client;

import es.ramondin.performance.modelOracle.views.PanelLinVORowImpl;
import es.ramondin.performance.modelOracle.views.common.PanelLinVO;

import java.util.ArrayList;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 30 09:08:54 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PanelLinVOClient extends ViewUsageImpl implements PanelLinVO {
    /**
     * This is the default constructor (do not remove).
     */
    public PanelLinVOClient() {
    }

    public Integer getNumLineasPanel() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getNumLineasPanel",null,null);
        return (Integer)_ret;
    }

    public ArrayList<PanelLinVORowImpl> getLineasPanel() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getLineasPanel",null,null);
        return (ArrayList<PanelLinVORowImpl>)_ret;
    }
}
