package es.ramondin.performance.modelOracle.views.client;

import es.ramondin.performance.modelOracle.views.common.ParametroVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 30 10:48:02 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ParametroVOClient extends ViewUsageImpl implements ParametroVO {
    /**
     * This is the default constructor (do not remove).
     */
    public ParametroVOClient() {
    }

    public String getValor(String param) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getValor",new String [] {"java.lang.String"},new Object[] {param});
        return (String)_ret;
    }
}
