package es.ramondin.performance.modelOracle.views.client;

import es.ramondin.performance.modelOracle.views.common.TurnoVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 13 10:19:39 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TurnoVOClient extends ViewUsageImpl implements TurnoVO {
    /**
     * This is the default constructor (do not remove).
     */
    public TurnoVOClient() {
    }

    public String[] getClavesTurnos() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getClavesTurnos",null,null);
        return (String[])_ret;
    }

    public Integer[] getIndicesTurnos() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getIndicesTurnos",null,null);
        return (Integer[])_ret;
    }
}
