package es.ramondin.performance.model.views;

import java.math.BigDecimal;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 24 18:30:40 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExcepcionVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RvarSecuen41 {
            public Object get(ExcepcionVORowImpl obj) {
                return obj.getRvarSecuen41();
            }

            public void put(ExcepcionVORowImpl obj, Object value) {
                obj.setRvarSecuen41((BigDecimal)value);
            }
        }
        ,
        RvarSeccion41 {
            public Object get(ExcepcionVORowImpl obj) {
                return obj.getRvarSeccion41();
            }

            public void put(ExcepcionVORowImpl obj, Object value) {
                obj.setRvarSeccion41((BigDecimal)value);
            }
        }
        ,
        RvarCelula141 {
            public Object get(ExcepcionVORowImpl obj) {
                return obj.getRvarCelula141();
            }

            public void put(ExcepcionVORowImpl obj, Object value) {
                obj.setRvarCelula141((BigDecimal)value);
            }
        }
        ,
        RvarCelula241 {
            public Object get(ExcepcionVORowImpl obj) {
                return obj.getRvarCelula241();
            }

            public void put(ExcepcionVORowImpl obj, Object value) {
                obj.setRvarCelula241((BigDecimal)value);
            }
        }
        ,
        RvarCelula341 {
            public Object get(ExcepcionVORowImpl obj) {
                return obj.getRvarCelula341();
            }

            public void put(ExcepcionVORowImpl obj, Object value) {
                obj.setRvarCelula341((BigDecimal)value);
            }
        }
        ,
        RvarCelula441 {
            public Object get(ExcepcionVORowImpl obj) {
                return obj.getRvarCelula441();
            }

            public void put(ExcepcionVORowImpl obj, Object value) {
                obj.setRvarCelula441((BigDecimal)value);
            }
        }
        ,
        RvarCelula541 {
            public Object get(ExcepcionVORowImpl obj) {
                return obj.getRvarCelula541();
            }

            public void put(ExcepcionVORowImpl obj, Object value) {
                obj.setRvarCelula541((BigDecimal)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(ExcepcionVORowImpl object);

        public abstract void put(ExcepcionVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int RVARSECUEN41 = AttributesEnum.RvarSecuen41.index();
    public static final int RVARSECCION41 = AttributesEnum.RvarSeccion41.index();
    public static final int RVARCELULA141 = AttributesEnum.RvarCelula141.index();
    public static final int RVARCELULA241 = AttributesEnum.RvarCelula241.index();
    public static final int RVARCELULA341 = AttributesEnum.RvarCelula341.index();
    public static final int RVARCELULA441 = AttributesEnum.RvarCelula441.index();
    public static final int RVARCELULA541 = AttributesEnum.RvarCelula541.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ExcepcionVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute RvarSecuen41.
     * @return the RvarSecuen41
     */
    public BigDecimal getRvarSecuen41() {
        return (BigDecimal) getAttributeInternal(RVARSECUEN41);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RvarSecuen41.
     * @param value value to set the  RvarSecuen41
     */
    public void setRvarSecuen41(BigDecimal value) {
        setAttributeInternal(RVARSECUEN41, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RvarSeccion41.
     * @return the RvarSeccion41
     */
    public BigDecimal getRvarSeccion41() {
        return (BigDecimal) getAttributeInternal(RVARSECCION41);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RvarSeccion41.
     * @param value value to set the  RvarSeccion41
     */
    public void setRvarSeccion41(BigDecimal value) {
        setAttributeInternal(RVARSECCION41, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RvarCelula141.
     * @return the RvarCelula141
     */
    public BigDecimal getRvarCelula141() {
        return (BigDecimal) getAttributeInternal(RVARCELULA141);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RvarCelula141.
     * @param value value to set the  RvarCelula141
     */
    public void setRvarCelula141(BigDecimal value) {
        setAttributeInternal(RVARCELULA141, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RvarCelula241.
     * @return the RvarCelula241
     */
    public BigDecimal getRvarCelula241() {
        return (BigDecimal) getAttributeInternal(RVARCELULA241);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RvarCelula241.
     * @param value value to set the  RvarCelula241
     */
    public void setRvarCelula241(BigDecimal value) {
        setAttributeInternal(RVARCELULA241, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RvarCelula341.
     * @return the RvarCelula341
     */
    public BigDecimal getRvarCelula341() {
        return (BigDecimal) getAttributeInternal(RVARCELULA341);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RvarCelula341.
     * @param value value to set the  RvarCelula341
     */
    public void setRvarCelula341(BigDecimal value) {
        setAttributeInternal(RVARCELULA341, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RvarCelula441.
     * @return the RvarCelula441
     */
    public BigDecimal getRvarCelula441() {
        return (BigDecimal) getAttributeInternal(RVARCELULA441);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RvarCelula441.
     * @param value value to set the  RvarCelula441
     */
    public void setRvarCelula441(BigDecimal value) {
        setAttributeInternal(RVARCELULA441, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RvarCelula541.
     * @return the RvarCelula541
     */
    public BigDecimal getRvarCelula541() {
        return (BigDecimal) getAttributeInternal(RVARCELULA541);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RvarCelula541.
     * @param value value to set the  RvarCelula541
     */
    public void setRvarCelula541(BigDecimal value) {
        setAttributeInternal(RVARCELULA541, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
