package es.ramondin.performance.model.views.client;

import es.ramondin.performance.model.views.common.ExcepcionVO;

import java.math.BigDecimal;

import java.util.ArrayList;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 24 17:38:56 CEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExcepcionVOClient extends ViewUsageImpl implements ExcepcionVO {
    /**
     * This is the default constructor (do not remove).
     */
    public ExcepcionVOClient() {
    }

    public Boolean hayExcepciones() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"hayExcepciones",null,null);
        return (Boolean)_ret;
    }

    public ArrayList<BigDecimal> getCelulasExcepcion() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getCelulasExcepcion",null,null);
        return (ArrayList<BigDecimal>)_ret;
    }
}
